/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:1803ec34-c8aa-4a58-9bce-6c54c53d2f84",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_i1EOVdV21",
    "aws_user_pools_web_client_id": "240qbbk1uk0mlmulc0f41kpg3o",
    "oauth": {
        "domain": "amplifyapp882158dc-882158dc-master.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://master.daicopkrolqcq.amplifyapp.com/",
        "redirectSignOut": "https://master.daicopkrolqcq.amplifyapp.com/,https://master.daicopkrolqcq.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://trupfnoj3bdujjqlhwgnz5o26u.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-aoknq7w2ljctjkog4xqjq4adlq",
    "aws_user_files_s3_bucket": "amplifyapp1dff591d8f724d7e88bb4ac397abc014112631-master",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
